name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.4
        with:
          jekyll_src: /
          target_branch: published
        env:
          JEKYLL_PAT: ${{ github.actor }}:${{ github.token }}