name: Build and deploy Jekyll site to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: helaili/jekyll-action@v2
        with:
          jekyll_src: .
          token: ${{ secrets.GITHUB_TOKEN }}
